name: Deploy via SSH

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: SSH to server
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.HOST }} # Adres IP serwera lub nazwa hosta
          username: ${{ secrets.USERNAME }} # Użytkownik SSH (np. 'deploy')
          key: ${{ secrets.SSH_PRIVATE_KEY }} # Klucz prywatny SSH
          passphrase: ${{ secrets.SSH_PASSPHRASE }} # (Opcjonalne) Hasło klucza
          port: 22
          script: |
            echo "Deployment in progress"
            # Twoje polecenia tutaj
